export type MarkerCategory = 'infrastructure' | 'sanitation' | 'safety' | 'medical' | 'blood' | 'volunteer';

export interface MapMarker {
  id: number;
  lat: number;
  lng: number;
  title: string;
  category: MarkerCategory;
  status: 'open' | 'in-progress' | 'resolved';
  priority: 'low' | 'medium' | 'high';
  reportedBy: string;
  time: string;
  upvotes: number;
  description: string;
}

export const categoryConfig: Record<
  MarkerCategory,
  { label: string; color: string; icon: string }
> = {
  infrastructure: { label: 'Infrastructure', color: '#0ea5e9', icon: '🏗️' },
  sanitation: { label: 'Sanitation', color: '#22c55e', icon: '🧹' },
  safety: { label: 'Safety', color: '#f59e0b', icon: '⚠️' },
  medical: { label: 'Medical Camp', color: '#8b5cf6', icon: '🏥' },
  blood: { label: 'Blood Request', color: '#ef4444', icon: '🩸' },
  volunteer: { label: 'Volunteer', color: '#ec4899', icon: '🤝' },
};

export const mapMarkers: MapMarker[] = [
  {
    id: 1,
    lat: 18.5204,
    lng: 73.8567,
    title: 'Pothole on MG Road',
    category: 'infrastructure',
    status: 'in-progress',
    priority: 'high',
    reportedBy: 'Aarav S.',
    time: '2h ago',
    upvotes: 24,
    description: 'Large pothole near the traffic signal causing traffic congestion and vehicle damage.',
  },
  {
    id: 2,
    lat: 18.5308,
    lng: 73.8449,
    title: 'Streetlight not working',
    category: 'safety',
    status: 'open',
    priority: 'medium',
    reportedBy: 'Priya M.',
    time: '5h ago',
    upvotes: 18,
    description: 'Streetlight has been out for 3 days on Sector 7 main road, creating unsafe conditions at night.',
  },
  {
    id: 3,
    lat: 18.5102,
    lng: 73.8625,
    title: 'Water leakage near park',
    category: 'infrastructure',
    status: 'resolved',
    priority: 'low',
    reportedBy: 'Rahul K.',
    time: '1d ago',
    upvotes: 31,
    description: 'Continuous water leakage from a broken pipe near the community park entrance.',
  },
  {
    id: 4,
    lat: 18.5176,
    lng: 73.8512,
    title: 'Garbage collection delayed',
    category: 'sanitation',
    status: 'in-progress',
    priority: 'medium',
    reportedBy: 'Anita S.',
    time: '1d ago',
    upvotes: 12,
    description: 'Garbage in Ward 12 has not been collected for 5 days, causing hygiene concerns.',
  },
  {
    id: 5,
    lat: 18.5392,
    lng: 73.8734,
    title: 'Free Health Check-up Camp',
    category: 'medical',
    status: 'open',
    priority: 'high',
    reportedBy: 'Seva Foundation',
    time: '3h ago',
    upvotes: 45,
    description: 'Medical camp scheduled for Sunday, July 14 at Community Hall, Ward 7. Free check-ups for all.',
  },
  {
    id: 6,
    lat: 18.5074,
    lng: 73.8398,
    title: 'Urgent: O+ blood needed',
    category: 'blood',
    status: 'open',
    priority: 'high',
    reportedBy: 'Rahul K.',
    time: '2h ago',
    upvotes: 38,
    description: 'Urgent need for O+ blood at City Hospital for emergency surgery. 2 units required.',
  },
  {
    id: 7,
    lat: 18.5245,
    lng: 73.8656,
    title: 'Broken bench at bus stop',
    category: 'infrastructure',
    status: 'open',
    priority: 'low',
    reportedBy: 'Vikram J.',
    time: '2d ago',
    upvotes: 7,
    description: 'Public bench at Main Street bus stop is broken and needs replacement.',
  },
  {
    id: 8,
    lat: 18.5331,
    lng: 73.8598,
    title: 'Volunteer cleanup drive',
    category: 'volunteer',
    status: 'open',
    priority: 'medium',
    reportedBy: 'Helping Hands NGO',
    time: '6h ago',
    upvotes: 29,
    description: 'Community cleanup drive this Saturday at Park Plaza. 34 volunteers already joined.',
  },
  {
    id: 9,
    lat: 18.5145,
    lng: 73.8473,
    title: 'Damaged road divider',
    category: 'safety',
    status: 'open',
    priority: 'high',
    reportedBy: 'Karan V.',
    time: '8h ago',
    upvotes: 15,
    description: 'Road divider on Highway 4 is damaged, causing vehicles to cross into oncoming traffic.',
  },
  {
    id: 10,
    lat: 18.5289,
    lng: 73.8681,
    title: 'Overflowing drain',
    category: 'sanitation',
    status: 'in-progress',
    priority: 'high',
    reportedBy: 'Meera P.',
    time: '12h ago',
    upvotes: 22,
    description: 'Drain near Sector 4 market is overflowing, creating unsanitary conditions.',
  },
  {
    id: 11,
    lat: 18.5198,
    lng: 73.8423,
    title: 'Eye Screening Drive',
    category: 'medical',
    status: 'open',
    priority: 'medium',
    reportedBy: 'Vision Care NGO',
    time: '1d ago',
    upvotes: 19,
    description: 'Free eye screening camp on July 20 at Govt School, Sector 4. 10 volunteer slots open.',
  },
  {
    id: 12,
    lat: 18.5412,
    lng: 73.8489,
    title: 'B- blood needed',
    category: 'blood',
    status: 'open',
    priority: 'urgent' as 'high',
    reportedBy: 'Meera P.',
    time: '4h ago',
    upvotes: 41,
    description: 'B- blood required at Apollo Care for a patient undergoing treatment. 1 unit needed.',
  },
];
